config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }
  root to: 'home#index'

  resources :events
  resources :competitions
end

app/models/competition.rb
# == Schema Information
#
# Table name: competitions
#
#  id                 :integer          not null, primary key
#  description        :string(255)
#  sport_id           :integer
#  event_date_id      :integer
#  season_desc        :string(255)
#  season_code        :string(255)
#  summer_season_flag :string(255)
#  summer_season_desc :string(255)
#  summer_season_code :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file         :string(255)
#

class Competition < ApplicationRecord
  belongs_to :sport

  belongs_to :event_date
  has_many :events
  has_many :event_types
  has_many :fixtures
  has_many :player_dims
  has_many :player_facts
  has_many :team_dims
  has_many :team_facts
  has_many :photos, as: :imageable, dependent: :destroy

  mount_uploader :image_file, ImageUploader
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :load_competition, only: [:show, :destroy]

  def index
    @competitions = Competition.all
  end

  def show
    @events = @competition.events
    @photos = @competition.photos
    @team_dims = @competition.team_dims.includes(:team_facts)
  end

  private

  def load_competition
    @competition = Competition.find(params[:id])
  end
end

app/views/competitions/_competition.html.slim
figure
  = image_tag(competition.image_file.url) if competition.image_file.present?
  figcaption= link_to competition.description, competition_path(competition)

app/views/competitions/_event.html.slim
p= link_to event.description, event_path(event)

app/views/competitions/_league_table.html.slim
table
  caption Tournament table
  tr
    th #
    th
    th Team
    th PI
    th W
    th D
    th L
    th F
    th A
    th GD
    th Pts
    th Last6

  = render partial: 'table', collection: @team_dims, as: :team_dim

app/views/competitions/_table.html.slim
- stat = team_dim.team_facts.where(competition_id: team_dim.competition_id).first
tr
  td= stat.league_position
  td=image_tag(team_dim.logo_url)
  td= team_dim.team_name
  td= stat.played
  td= stat.win
  td= stat.draw
  td= stat.loss
  td= stat.goals_for
  td= stat.goal_diff
  td= stat.home_points
  td= stat.points
  td

app/views/competitions/index.html.slim
= render @competitions

app/views/competitions/show.html.slim
.event
  = render partial: 'event', collection: @events
.league
  p= @competition.description
  p= @competition.season_desc
  p= @competition.season_code
  = render 'league_table'
.photos
  - if @photos.present?
    - @photos.each do |photo|
      = image_tag(photo.url)